#!/bin/sh
#curl -s -S -v -X GET http://localhost:8080/test

# for Admin to manipulate restaurants

curl -s -S -X POST -H "Content-Type: application/json" -d '{"name":"Restaurant 1"}' http://localhost:8080/restaurant
curl -s -S -X POST -H "Content-Type: application/json" -d '{"name":"Restaurant 2"}' http://localhost:8080/restaurant
curl -s -S -X POST -H "Content-Type: application/json" -d '{"name":"Restaurant 3"}' http://localhost:8080/restaurant
curl -s -S -X POST -H "Content-Type: application/json" -d '{"id":3, "name":"Restaurant 3 updated"}' http://localhost:8080/restaurant
curl -s -S -X GET http://localhost:8080/restaurant/3
curl -s -S -X DELETE http://localhost:8080/restaurant/2
curl -s -S -X GET http://localhost:8080/restaurant

# for Admin to manipulate dishes

curl -s -S -X POST -H "Content-Type: application/json" -d '{"name":"Dish 1", "price":12.34}' http://localhost:8080/dish
curl -s -S -X POST -H "Content-Type: application/json" -d '{"name":"Dish 2", "price":23.45}' http://localhost:8080/dish
curl -s -S -X POST -H "Content-Type: application/json" -d '{"name":"Dish 3", "price":34.56}' http://localhost:8080/dish
curl -s -S -X POST -H "Content-Type: application/json" -d '{"name":"Dish 4", "price":45.67}' http://localhost:8080/dish
curl -s -S -X POST -H "Content-Type: application/json" -d '{"id":3, "name":"Dish 3 updated", "price":99.99}' http://localhost:8080/dish
curl -s -S -X GET http://localhost:8080/dish/3
curl -s -S -X DELETE http://localhost:8080/dish/2
curl -s -S -X GET http://localhost:8080/dish

# for Admin to manipulate menus

curl -s -S -X POST -H "Content-Type: application/json" -d '{"restaurant":1,"menuDate":"2017-03-06","dishes":[1,3]}' http://localhost:8080/menu
curl -s -S -X POST -H "Content-Type: application/json" -d '{"restaurant":3,"menuDate":"2017-03-06","dishes":[3,4]}' http://localhost:8080/menu
curl -s -S -X POST -H "Content-Type: application/json" -d '{"id":2,"restaurant":3,"menuDate":"2017-03-06","dishes":[1,4]}' http://localhost:8080/menu
curl -s -S -X GET http://localhost:8080/menu
curl -s -S -X GET http://localhost:8080/menu?date=2017-03-06

# for Admin and Users to vote

