DROP TABLE IF EXISTS DISH CASCADE;
DROP TABLE IF EXISTS MENU CASCADE;
DROP TABLE IF EXISTS MENU_DISHES CASCADE;
DROP TABLE IF EXISTS RESTAURANT CASCADE;
DROP TABLE IF EXISTS USER CASCADE;
DROP TABLE IF EXISTS VOTE CASCADE;
CREATE TABLE DISH(
    ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL
);
ALTER TABLE DISH ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(ID);
CREATE TABLE MENU(
    ID INTEGER AUTO_INCREMENT,
    DATE DATE NOT NULL,
    RESTAURANT_ID INTEGER NOT NULL
);
ALTER TABLE MENU ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(ID);
CREATE TABLE MENU_DISHES(
    MENU_ID INTEGER NOT NULL,
    DISHES_ID INTEGER NOT NULL
);
CREATE TABLE RESTAURANT(
    ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);
ALTER TABLE RESTAURANT ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY(ID);
CREATE TABLE USER(
    ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255)
);
ALTER TABLE USER ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(ID);
CREATE TABLE VOTE(
    ID INTEGER AUTO_INCREMENT,
    DATE DATE NOT NULL,
    RESTAURANT_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL
);
ALTER TABLE VOTE ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY(ID);
ALTER TABLE VOTE ADD CONSTRAINT CONSTRAINT_6 UNIQUE(RESTAURANT_ID, DATE, USER_ID);
ALTER TABLE USER ADD CONSTRAINT CONSTRAINT_7 UNIQUE(NAME);
ALTER TABLE MENU ADD CONSTRAINT CONSTRAINT_8 UNIQUE(RESTAURANT_ID, DATE);
ALTER TABLE VOTE ADD CONSTRAINT CONSTRAINT_9 FOREIGN KEY(RESTAURANT_ID) REFERENCES RESTAURANT(ID);
ALTER TABLE MENU ADD CONSTRAINT CONSTRAINT_10 FOREIGN KEY(RESTAURANT_ID) REFERENCES RESTAURANT(ID);
ALTER TABLE MENU_DISHES ADD CONSTRAINT CONSTRAINT_11 FOREIGN KEY(MENU_ID) REFERENCES MENU(ID);
ALTER TABLE MENU_DISHES ADD CONSTRAINT CONSTRAINT_12 FOREIGN KEY(DISHES_ID) REFERENCES DISH(ID);
ALTER TABLE VOTE ADD CONSTRAINT CONSTRAINT_13 FOREIGN KEY(USER_ID) REFERENCES USER(ID);